name: theme_manager_plus
description: "No More theme data. Customise your theme with your theme class "
version: 0.0.4
repository: "https://github.com/Oauth-Celestial/theme_manager_plus"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
